spring:
  datasource:
    url: jdbc:mysql://10.234.208.173:3306/blog?characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: bingzibing
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 300000
cron:
  updateTestStatTask: "0 0/5 * * * ?"